services:
  my-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ENV=production
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: bRDAzUBjPalRYsBnHaylkHcYZBapetBX
      MYSQL_DATABASE: railway
    networks:
      - my-network